### PR TITLE
Server.subscribe

### LINKED ISSUE #408: Server Side Subscribe
To attach logic into message publishes on different topics, we have three options:

1) `server.on( 'published', ...)`: This way your handlers should pattern match all input messages, not seem good in real world production.

2) Create a MQTT client, connect it to the local server and subscribe on desired topic to receive only needed messages...

3) `server.subscribe` which does the above but inside the broker, no need to create a separate client.

Should we add the last one into mosca? I want to hear your comments on the best solution @mcollina

### PR DESCRIPTION
**Pull request by behrad**
provide a subscribe method using ascoltatori backend. Closes #408

### CODE REVIEW

**Comment by mcollina** [comment]
I would just throw in a little unit test for the new API.

**Comment by mcollina** [comment]
Any update on this?

**Comment by behrad** [comment]
I was busy @mcollina , sorry for being late, will update ASAP

**Comment by mcollina** [comment]
Can I get a couple of tests for this, so I add it to #464 ?

**Comment by behrad** [comment]
this PR seemed abit old, I created a new one based on your master #472 However there's also a conflict! I can't say why!?

**Comment by mcollina** [comment]
It's not based on latest master.

**Pull request closed without merging**
