### PR TITLE
[redis-persistence] Improve storePacket performance

### PR DESCRIPTION
**Pull request by behrad**
Changing storePacket to a lua script totally improved storeOffline step for a very long list of client matches :)

### CODE REVIEW

**Comment by behrad** [comment]
`storeOffline` lua script freezes redis when running for a large set of subscriptions (multiple hundred thousands), since redis is not responsive when executing lua scripts. 
This bothers clients connecting...

One simple choice would be reverting the lua script to multi (as it was before) + pipelining 
The other choice is to split read-only operations (subscriptionLookup + forwardRetain, ...) to a read-only slave redis instance. However there can still exist the same problem for other concurrent write operations from redis persistence.

**Comment by mcollina** [comment]
Let's revert to multi+pipelinining with ioredis then.

**Comment by mcollina** [comment]
you can close this PR and send a new one against #464

**Comment by behrad** [comment]
we can currently close this in favor of #455

**Pull request closed without merging**
