### PR TITLE
adding a Raspberry Pi specific Dockerfile

### PR DESCRIPTION
**Pull request by joelash**

### CODE REVIEW

**Comment by mcollina** [comment]
How can I automate the build with Docker Hub to have both of these up and running from this github repo?
I'm really strained with time and doing manual builds takes time (and bandwidth).

**Comment by joelash** [comment]
Have you taken a look at this doc? Just doing a quick skim it looks like how you would do it? https://docs.docker.com/docker-hub/builds/

I can try it on my branch this weekend and let you know how it goes.

**Comment by mcollina** [comment]
You are right, it's probably doable. I'll give it a spin asap.

**Comment by mcollina** [comment]
This is failing the automatic build on Docker Hub: https://hub.docker.com/r/matteocollina/mosca/builds/bluamrqu3hxbpqbjd2reffd/. Any clue?

**Comment by joelash** [comment]
I came across this in another repo I just added a similar PR for, dockerhub only builds on x86 and not on ARM. Which is well obvious now that I know :-) I'm looking into an alternative way to get it to automatically build. I'll keep you posted.

**Pull request merged**
