### PR TITLE
Add close reason to the clientDisconnected event

### PR DESCRIPTION
**Pull request by behrad**

### CODE REVIEW

**Comment by mcollina** [comment]
Either the reason is an error, or the reason is a string, having both is not ok.

Also, unit tests are missing.

**Comment by behrad** [comment]
How would like to unify them? Is always string OK? String messages/error.message?

**Comment by mcollina** [comment]
Thanks for moving all of them to strings, but I think the best way to support this is via the signature  `err, reason`, where `reason` is `'error'` if `err` is present. This is the most backward-compabile way for achieving this.

**Comment by behrad** [comment]
> Thanks for moving all of them to strings, but I think the best way to support this is via the signature  err, reason, where reason is 'error' if err is present

You mean `on('clientDisconnected', (client, err, reason) => {})`? 
I should say in many cases there's no `err` object and we have a normal connection close.
Even `on('clientDisconnected', (client, reason, err) => {})` is not pretty.



> This is the most backward-compabile way for achieving this

This is a new feature in Mosca, what you want to achieve by backward-compatible here?

**Comment by behrad** [comment]
@mcollina I'm ready to make if final based on your opinion.

**Comment by mcollina** [comment]
You are right, this is good to go.

**Comment by Urmik** [comment]
Hello,

By using 
that.close(null,"err_message");

Where can I get this err_message in client side?
I have tried it in .Net (M2MQTT) client library. But I didn't get it in connection close event..

**Pull request merged**
