### PR TITLE
New PR (=455) against v2-dev

### PR DESCRIPTION
**Pull request by behrad**
Does this help @mcollina ?

### CODE REVIEW

**Comment by mcollina** [comment]
It does not apply cleanly :/, can you sort this out?

**Comment by behrad** [comment]
Why not?

1) KEYS is changed to SCAN
2) Qlobber version is upgraded
3) storeOfflinePacket signature is added with a new "pipline" argument. 

Diffs of two files are clear for me :) How do you want me to do this?

**Comment by mcollina** [comment]
Not sure why: check out v2-dev, merge these changes in, and push to a new branch on a new PR?

**Comment by behrad** [comment]
closing in favor of #499

**Pull request closed without merging**
