### PR TITLE
Enhance stats

### PR DESCRIPTION
**Pull request by behrad**
1. adds lastIntervalConnectedClient for last Xmin connected clients stat
2. fixes publish stat to just count messages published to user namespace
3. adds clients/maximum stat

### CODE REVIEW

**Comment by mcollina** [comment]
Unit tests?
Il giorno sab 18 lug 2015 alle 21:23 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
I tested all this manually, however found no related tests in mosca tests.

**Comment by behrad** [comment]
this is ready @mcollina

**Comment by mcollina** [comment]
Awesome!!

**Pull request merged**
