### PR TITLE
fixes #271

### LINKED ISSUE #271: Duplication of some forwardOfflineMessages?
I see my client occasionally receives an offline multiple times (within 60-70 milliseconds), it seems mosca is forwarding a message twice!? 
I can't find a clue looking at the code @mcollina

### PR DESCRIPTION
**Pull request by behrad**
it simply guards against adding a single (sub,id) multiple times `into _subMatcher`

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test for this situation?

**Comment by behrad** [comment]
We should write a failing test which happens on clustered mosca.

have you any test case code sample using clustered mosca?

**Comment by behrad** [comment]
or we can simulate the environment manipulating `that._subMatcher` by hand

**Comment by mcollina** [comment]
There are some for Ascoltatori, but not for Mosca: https://github.com/mcollina/ascoltatori/blob/master/test/redis_ascoltatore_spec.js#L27-L44.

**Comment by behrad** [comment]
Would you please check this and merge if it is OK @mcollina

**Comment by behrad** [comment]
WoW, my typo, commit message should have been "added test for #271"

**Comment by mcollina** [comment]
No problem and thanks for fixing this!

**Comment by behrad** [comment]
thank you @mcollina

**Pull request merged**
