### PR TITLE
publish client disconnect to $SYS

### PR DESCRIPTION
**Pull request by behrad**

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?
Il giorno sab 18 lug 2015 alle 21:24 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
tested this locally, but not have all needed stuff (like mongo, ...) on my current machine.
No related tests found in mosca tests

**Comment by behrad** [comment]
seems mosca mongo tests are failing on mongo 3.0.3 with `MongoError: no collection`
Is this a mongo driver issue?

**Comment by behrad** [comment]
used a mongo 2.8 to run the tests

**Comment by mcollina** [comment]
Tests are passing on Travis, so I'm good :D. Not sure what's the problem, but this looks good :)

**Pull request merged**
