### PR TITLE
V2 dev

### PR DESCRIPTION
**Pull request by mcollina**
Includes #449 #455 #456.

Drops support for node v0.10 and add support for v6.

I need to do the same for ascoltatori :).

### CODE REVIEW

**Comment by mcollina** [comment]
This might require some refactoring on the travis CI, as mongo tests are becoming really unstable. Part of this are problem at code level, which are hardly solvable without a substantial rewrite and massive API change (that I already did for Aedes, coming soon, but we need to land this first).

**Comment by behrad** [comment]
Also seems a microtime incompatibility with node v6

**Comment by mcollina** [comment]
@behrad an you please send me a a PR against this one where you revert back to https://github.com/mcollina/mosca/pull/455

**Comment by behrad** [comment]
> @behrad an you please send me a a PR against this one where you revert back to #455

Isn't #455 what you want @mcollina ?

**Comment by behrad** [comment]
this is my latest commit there: https://github.com/mcollina/mosca/pull/455/commits/25e158fcdf43a0adc46e24a6dbe9e495eb890bfa

**Comment by mcollina** [comment]
@behrad merges 3 prs. how to undo the one with the lua script? (little time, sorry)

**Pull request merged**
