### PR TITLE
upgrade deps for iojs compatibility

### PR DESCRIPTION
**Pull request by boneskull**
depends on various other PRs:

- redis/hiredis-node#87
- mcollina/ascoltatori#117
- mcollina/async_bench#4

may need to send a PR to chrisa/node-dtrace-provider and trentm/node-bunyan as well.

tests need addressing: "mosca.Server - MQTT backend should pass the backend settings to ascoltatori.build" failure

### CODE REVIEW

**Comment by mcollina** [comment]
Tests fails badly, can you please make sure that the tests pass with these new dependencies?
Also, can you add iojs to .travis.yml?

**Comment by boneskull** [comment]
@mcollina I have no idea how to fix the test, but I can modify `.travis.yml` for you.

I was hoping to use Mosca as a MQTT broker, but it seems that the server example in the `mqtt` package will do for now.

**Comment by mcollina** [comment]
Thanks so much for the help, you got me into releasing a version compatible with iojs v2. It's almost there, I'm waiting for travis to finish running.

**Comment by boneskull** [comment]
@mcollina Awesome!  Glad I could help.  Can't wait to use Mosca!

**Comment by mcollina** [comment]
released.

**Pull request merged**
