### PR TITLE
fixes #616 and some lintings

### LINKED ISSUE #616: Retrieves messages in mongo after reconnect
Hello,
Retrieve messages in mongo after reconnecting.
I have problem to retrieve messages after to reconnect with broker Mosca.
The messages are saved for send to client after to reconnect, but the client receive only a buffer
with length 0.
With redis I dont have any problems.

broker code:  
``` let mosca = require('mosca');  
let redis = require('redis');  
//Mongodb setting persistence   
let mongoSetting = {
    type: 'mongo',
    url: 'mongodb://localhost:27017/mqtt',
    pubsubCollection: 'mosca',
    mongo: {}
}; 
let settings = {
    port: 1884,
    backend: mongoSetting,
    persistence: {
        factory: mosca.persistence.Mongo,
        url: 'mongodb://localhost:27017/mqtt',
        ttl: {
            subscriptions: 60 * 60 * 1000,
            packets: 60 * 60 * 1000
        }
    }
}; 
//Redis setting persistence
// let redisSetting = {
//     type: 'redis',
//     redis: redis,
//     port: 6379,
//     return_buffers: true, // to handle binary payloads
//     host: "localhost"
// };
// let settings = {
//     port: 1884,
//     backend: redisSetting,
//     persistence: {
//         factory: mosca.persistence.Redis
//     }
// }; 
let setup = () => {
    console.log('Mosca server is up and running');	
};
let server = new mosca.Server(settings);
server.on('ready', setup);
server.on('clientConnected', (client) => {	
    console.log('client connected', client.id);
});
setTimeout(() => {
    let i = 1;
    let interval = setInterval(() => {
        let data = JSON.stringify({data: 'hello client ' + i});
        let message = {
            topic: '/agents',
            payload: data,
            qos: 1,
            retain: false
        };
        server.publish(message, function () {
            console.log('send message.! ' + i);
        });
        i += 1;
        if (i === 6) {
            clearInterval(interval);
        }
    }, 500);
}, 10000);
// fired when a message is received
server.on('published', (packet, client) => {
    if (client) {
        console.log('published topic from client: ', packet.topic);
        let message = packet.payload;
        console.log('published message from client: ', typeof message, message);
        let messageObject = JSON.parse(message);
        console.log('published messageObject from client: ', typeof messageObject, messageObject);
    } else {
        console.log('published server: ', packet);
    }
});
```
  

client code:  
```let mqtt = require('mqtt');
let param = process.argv[2];
let clientId = param || 'mqttjs_' + Math.random().toString(16).substr(2, 8);
let host = 'mqtt://localhost:1884';
let options = {
    clientId: clientId,
    clean: false
};
let client = mqtt.connect(host, options);
client.on('error', function (err) {
    console.log(err);
    client.end();
});
client.on('connect', function (params) {
    client.subscribe('/agents', {qos: 1});
    console.log('client connected:' + clientId);
    console.log(params);
});
client.on('message', function (topic, message, packet) {
    if (message.length > 0) {
        let messageParsed = JSON.parse(message);
        console.log('Received Message:= ' + messageParsed.toString() + '\nOn topic:= ' + topic);
        console.log(messageParsed);
    } else {
        console.log('message length 0. from: ', topic);
    }
});
client.on('close', function () {
    console.log(clientId + ' disconnected');
});```

### PR DESCRIPTION
**Pull request by mitsos1os**
Fix for the #616 issue.
Also pre-commit hook was failing on some other files... Fixed them also...

### CODE REVIEW

**Comment by mcollina** [comment]
Tests are failiing.

**Comment by mitsos1os** [comment]
Sorry! I accidentally replaced a linting error for return with a break... Should be okay now!

**Comment by mcollina** [comment]
THanks!

**Comment by mitsos1os** [comment]
You're welcome!

**Pull request merged**
