### PR TITLE
using newPacket instead of packet for publish

### PR DESCRIPTION
**Pull request by paularmand**
@mcollina as requested a PR for the proposed change.

### CODE REVIEW

**Comment by mcollina** [comment]
What are you trying to achieve with this? I remember there was a reason why I added that `newPacket`, but tests are passing anyway.

**Comment by paularmand** [comment]
Exactly that, newPacket isn't used anymore in the original code, only packet is used, making the creation of the newPacket ineffective. As I understand javascript scoping, packet is within scope of the publish function, so that's why it's still working, but any change to the newPacket variable will not be propagated. The reason I'm stating this is that I was trying to help out in https://github.com/mcollina/mosca/issues/368 , and was suggesting to change the payload in the newPacket variable to the OP.

**Comment by mcollina** [comment]
It's used here: https://github.com/mcollina/mosca/blob/master/lib/server.js#L345, and its unique id is used here: https://github.com/mcollina/mosca/blob/master/lib/server.js#L338.

**Comment by paularmand** [comment]
True, newPacket is hence used for the persistence layer, but the original packet is still published via ascoltatori.

**Comment by mcollina** [comment]
But that won't help overriding the payload. These needs to be changed as well: https://github.com/mcollina/mosca/blob/master/lib/client.js#L106-L107.

**Comment by paularmand** [comment]
Yes, that's quite possible. I 've had to change the forward function too in client.js for my use case. Something that I already pointed out to the OP in https://github.com/mcollina/mosca/issues/368. I was referring there to the fact that the client.js file has it's own packet structure, and uses that.

**Comment by mcollina** [comment]
Merged and released :)

**Comment by paularmand** [comment]
Thanks !

**Pull request merged**
