### PR TITLE
add tests for enrich subscription and unsubscriptions event

### PR DESCRIPTION
**Pull request by behrad**
tests added for #314, should be passing now

### CODE REVIEW

**Comment by mcollina** [comment]
Tests are failing on Travis https://travis-ci.org/mcollina/mosca/builds/71637820

**Comment by behrad** [comment]
shouldn't!

**Comment by behrad** [comment]
Weird! My local branch is passing @mcollina , and the travis build https://travis-ci.org/mcollina/mosca/jobs/71645131#L1038 reports an error on abstract_server.js:136 whereas my abstract_server is https://github.com/adpdigital/mosca/blob/enrich_subscibe_sysevent/test/abstract_server.js#L136

Can you please manually merge and test !?

**Comment by mcollina** [comment]
I checked trying a manual merge, and this is failing here too:

```
  1) mosca.Server should publish each subscribe to '$SYS/{broker-id}/new/subscribes':
     Uncaught SyntaxError: Unexpected token m
      at Object.parse (native)
      at EventEmitter.<anonymous> (test/abstract_server.js:136:26)
      at lib/server.js:335:16
      at EventEmitter.Server.published (lib/server.js:370:3)
      at Immediate._onImmediate (lib/server.js:333:14)
```

**Comment by behrad** [comment]
whats your `test/abstract_server.js:136:26` @mcollina I can't figure this out! looks strange to me

**Comment by mcollina** [comment]
Here it is:   
```js
   instance.once("published", function(packet) {
      expect(packet.topic).to.be.equal("$SYS/" + instance.id + "/new/subscribes");
      var payload = JSON.parse( packet.payload.toString() ); // this is 136
      publishedClientId = payload.clientId;
      expect(payload.topic).to.be.equal('hello');
      verify();
    });
```

It's parsing the payload of new/subscribes.

**Comment by behrad** [comment]
lemme check how come it may not be a JSON string!

**Comment by mcollina** [comment]
Any updates on this?

**Comment by behrad** [comment]
will find out this week...

**Comment by behrad** [comment]
There's a problem https://github.com/mcollina/mosca/pull/314 is missed in one of merges. I'll rebase and commit again.

**Pull request closed without merging**
