### PR TITLE
V1 dev

### PR DESCRIPTION
**Pull request by mcollina**
Please test, I'm bumping the major because we are soft-deprecating v0.10, meaning that it should work fine on 0.10, but you should update (and some adapeters, mainly 'filesystem' will not work).

I'll be publishing this as 1.0.0-pre1 shortly on NPM.

cc @behrad @psorowka

### CODE REVIEW

**Comment by psorowka** [comment]
Cool! I'm just a bit unsure about iojsv3. I removed it yesterday mainly because it was not in ascoltatori and because I had a test failure which later turned out to be that race condition. It's possible that we could take it back in both for ascoltatori and mosca.

On the other hand I figure most people who had switched to iojs are now on node4..

**Comment by psorowka** [comment]
lol.. I have to train: first read, then write.. just realized that you took out iojs completely

**Comment by mcollina** [comment]
Yeah, I'm not targeting iojs at all. If you are on iojs, switch to Node 4 or Node 5.

**Comment by psorowka** [comment]
leave me a note as soon as you have published, I'll update ascoltatori then.

**Pull request merged**
